version: "3.9"
services:
  backend-go:
    build: ./backend-go
    container_name: backend-go
    ports:
      - "8080:8080"
    networks:
      - appnet

  backend-python:
    build: ./backend-python
    container_name: backend-python
    ports:
      - "8000:8000"
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - appnet
    depends_on:
      - backend-go
      - backend-python

networks:
  appnet:
    driver: bridge
